export const data = [
    {
        id: 101,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        dayheader:['Student','firstAttendance','secondAttendance','dailyAttendance'],
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 102,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 103,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 104,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 105,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 106,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 107,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 108,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 109,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 110,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 111,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 112,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 113,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 114,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
]