export default {
    SHOW: "SHOW",
    HIDE: "HIDE",
    CLEARE_REDUX_STATE: "CLEAR_REDUX_STATE",
    LOAD_DATA:"LOAD_DATA",
    DAY_DATA: "DAY_DATA",
    WEAK_DATA: "WEAK_DATA",
    MONTH_DATA: "MONTH_DATA",
    CLASSVALUE1A: "CLASSVALUE1A",
    CLASSVALUE2B: "CLASSVALUE2B",
}